version: '3'

services:
  db:
    container_name: db
    image: mariadb
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    env_file: .env
    ports:
      - $DB_PORT:$DB_PORT

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
